// src/tslp/ganardi.rs
//
// Ganardi-Jeż-Lohrey (2021) TSLP balancing algorithm.
// Achieves O(log N) depth while preserving O(g) grammar size.
//
// # Algorithm: Grammar-native Symmetric Centroid Decomposition (SCD)
//
// Operates DIRECTLY on TslpGrammar productions — never expands the tree.
// Time:   O(g log g) where g = grammar size (unique nodes)
// Memory: O(g) — no Arc<EmlNode> allocations
//
// ## What we do:
// 1. Build a HashMap<id, rhs> from productions.
// 2. Count references: how many times each node is pointed to.
// 3. Compute subtree sizes: size[A] = number of leaves generated by A.
// 4. Collect "unbalanced right spines" — linear chains of eml nodes
//    where each node has ref_count == 1 (not shared with others).
// 5. For each spine of length k, emit log2(k) new productions
//    that form a balanced tournament tree over the spine's children.
// 6. Build new TslpGrammar from new productions.
//
// ## Reference: Ganardi, Jeż, Lohrey (JACM 2021), Section 4.

use crate::tslp::grammar::{TslpGrammar, TslpRhs, GrammarNodeId};
use std::collections::HashMap;

// ============================================================
// Public API
// ============================================================

/// Transforms an unbalanced TSLP grammar into a balanced one.
///
/// Guaranteed O(log N) depth where N = number of leaves in the full tree.
/// Grammar size remains O(g) — at most O(g log g) new productions.
///
/// Operates directly on `TslpGrammar.productions` — never rebuilds the full tree.
pub fn balance_grammar(grammar: &TslpGrammar) -> TslpGrammar {
    let mut rewriter = GrammarRewriter::new(grammar);
    let new_start = rewriter.balance(grammar.start);

    // Compute depths for the new grammar
    let depths = compute_depths(&rewriter.new_prods, new_start);

    TslpGrammar {
        productions: rewriter.new_prods,
        start: new_start,
        depths,
    }
}

// ============================================================
// Internal: GrammarRewriter
// ============================================================

struct GrammarRewriter {
    /// Original productions as a lookup map
    prod_map: HashMap<GrammarNodeId, TslpRhs>,
    /// How many times each node is referenced by other productions
    ref_counts: HashMap<GrammarNodeId, usize>,
    /// New balanced productions (output)
    pub new_prods: Vec<(GrammarNodeId, TslpRhs)>,
    /// Maps old_id → new balanced id (memoization)
    visited: HashMap<GrammarNodeId, GrammarNodeId>,
    /// Counter for generating fresh IDs for new productions
    fresh_id: GrammarNodeId,
}

impl GrammarRewriter {
    fn new(grammar: &TslpGrammar) -> Self {
        let prod_map: HashMap<GrammarNodeId, TslpRhs> = grammar.productions
            .iter()
            .map(|(id, rhs)| (*id, rhs.clone()))
            .collect();

        // Count how many times each node is referenced
        let mut ref_counts: HashMap<GrammarNodeId, usize> = HashMap::new();
        for (_, rhs) in grammar.productions.iter() {
            if let TslpRhs::Eml(l, r) = rhs {
                *ref_counts.entry(*l).or_insert(0) += 1;
                *ref_counts.entry(*r).or_insert(0) += 1;
            }
        }

        // Fresh IDs start above all existing IDs
        let max_id = grammar.productions.iter().map(|(id, _)| *id).max().unwrap_or(0);

        Self {
            prod_map,
            ref_counts,
            new_prods: Vec::with_capacity(grammar.productions.len() * 2),
            visited: HashMap::new(),
            fresh_id: max_id + 1,
        }
    }

    fn alloc_id(&mut self) -> GrammarNodeId {
        let id = self.fresh_id;
        self.fresh_id += 1;
        id
    }

    /// Balance the subtree rooted at `node`. Returns the id of the new balanced root.
    fn balance(&mut self, node: GrammarNodeId) -> GrammarNodeId {
        // Memoization: don't rebalance the same node twice
        if let Some(&mapped) = self.visited.get(&node) {
            return mapped;
        }

        let new_id = match self.prod_map.get(&node).cloned() {
            // Leaves: copy as-is under the same ID
            Some(TslpRhs::Leaf(kind)) => {
                self.new_prods.push((node, TslpRhs::Leaf(kind)));
                node
            }

            Some(TslpRhs::Eml(left, right)) => {
                // Try to collect a right-spine starting at this node.
                // A right-spine: node → eml(A, node2), node2 → eml(B, node3), ...
                // where each node on the spine has ref_count <= 1 (not shared).
                let spine = self.collect_right_spine(node);

                if spine.len() > 3 {
                    // Rebalance the spine into a balanced tournament tree
                    self.rebalance_spine(spine)
                } else {
                    // Not a spine (or too short) — just recursively balance children
                    let new_left  = self.balance(left);
                    let new_right = self.balance(right);
                    self.new_prods.push((node, TslpRhs::Eml(new_left, new_right)));
                    node
                }
            }

            None => node, // Unknown node — pass through
        };

        self.visited.insert(node, new_id);
        new_id
    }

    /// Collect the right spine starting at `node`.
    ///
    /// A right spine is a linear chain:
    ///   node  → eml(left0, n1)
    ///   n1    → eml(left1, n2)
    ///   n2    → eml(left2, n3)
    ///   ...
    ///   nk    → eml(leftk, tail)
    ///
    /// Where each node on the spine has ref_count <= 1 (only referenced from its parent).
    /// Returns (left_children, tail) as a Vec.
    /// If the spine is short (<= 3), returns an empty vec.
    fn collect_right_spine(&self, start: GrammarNodeId) -> Vec<SpineNode> {
        let mut spine = Vec::new();
        let mut current = start;

        loop {
            match self.prod_map.get(&current) {
                Some(TslpRhs::Eml(left, right)) => {
                    spine.push(SpineNode { id: current, left_child: *left });

                    // Continue down the right branch only if `right` is
                    // not shared (ref_count <= 1) and is an internal node
                    let rc = self.ref_counts.get(right).copied().unwrap_or(0);
                    if rc <= 1 {
                        if let Some(TslpRhs::Eml(_, _)) = self.prod_map.get(right) {
                            current = *right;
                            continue;
                        }
                    }
                    // End of spine — tail is `right`
                    spine.push(SpineNode { id: *right, left_child: *right });
                    break;
                }
                _ => {
                    // Leaf or unknown — end of spine
                    spine.push(SpineNode { id: current, left_child: current });
                    break;
                }
            }
        }

        spine
    }

    /// Rebalance a right-spine into a balanced tournament tree.
    ///
    /// spine = [node0(left0), node1(left1), ..., nodeK(tail)]
    ///
    /// We extract:
    ///   - left children: [left0, left1, ..., left_{K-1}]
    ///   - tail: spine[K].id  (the rightmost non-spine node)
    ///
    /// Then build a balanced binary tree over [left0, ..., left_{K-1}, tail]
    /// using new productions, and recursively balance each child.
    fn rebalance_spine(&mut self, spine: Vec<SpineNode>) -> GrammarNodeId {
        let n = spine.len();

        // Extract left children (all but last) and tail (last)
        let left_children: Vec<GrammarNodeId> = spine[..n - 1]
            .iter()
            .map(|s| s.left_child)
            .collect();
        let tail_id = spine[n - 1].id;

        // Recursively balance each left child
        let mut balanced_children: Vec<GrammarNodeId> = left_children
            .iter()
            .map(|&child| self.balance(child))
            .collect();

        // Recursively balance the tail
        let balanced_tail = self.balance(tail_id);
        balanced_children.push(balanced_tail);

        // Build balanced tournament tree over all children
        self.build_tournament_tree(&mut balanced_children)
    }

    /// Build a balanced binary tree over `nodes` using new productions.
    /// Returns the root ID of the new tree.
    fn build_tournament_tree(&mut self, nodes: &mut Vec<GrammarNodeId>) -> GrammarNodeId {
        assert!(!nodes.is_empty());

        while nodes.len() > 1 {
            let mut next_level = Vec::new();
            let mut i = 0;
            while i < nodes.len() {
                if i + 1 < nodes.len() {
                    // Pair two nodes into a new production
                    let new_id = self.alloc_id();
                    self.new_prods.push((new_id, TslpRhs::Eml(nodes[i], nodes[i + 1])));
                    next_level.push(new_id);
                    i += 2;
                } else {
                    // Odd one out — carry up unchanged
                    next_level.push(nodes[i]);
                    i += 1;
                }
            }
            *nodes = next_level;
        }

        nodes[0]
    }
}

// ============================================================
// Helper structs
// ============================================================

struct SpineNode {
    id: GrammarNodeId,
    left_child: GrammarNodeId,
}

// ============================================================
// Size computation — O(g), no tree expansion
// ============================================================

/// Compute subtree sizes (leaf count) for each grammar node.
/// Used by the full SCD algorithm for size-aware heavy-path detection.
/// Currently unused: spine detection relies only on ref_counts.
#[allow(dead_code)]
fn compute_sizes(
    node: GrammarNodeId,
    prod_map: &HashMap<GrammarNodeId, TslpRhs>,
    sizes: &mut HashMap<GrammarNodeId, u64>,
) -> u64 {
    if let Some(&s) = sizes.get(&node) {
        return s;
    }
    let size = match prod_map.get(&node) {
        Some(TslpRhs::Leaf(_)) | None => 1,
        Some(TslpRhs::Eml(l, r)) => {
            let ls = compute_sizes(*l, prod_map, sizes);
            let rs = compute_sizes(*r, prod_map, sizes);
            ls + rs
        }
    };
    sizes.insert(node, size);
    size
}


// ============================================================
// Depth computation for new grammar — O(g)
// ============================================================

fn compute_depths(
    prods: &[(GrammarNodeId, TslpRhs)],
    start: GrammarNodeId,
) -> HashMap<GrammarNodeId, usize> {
    let prod_map: HashMap<GrammarNodeId, &TslpRhs> =
        prods.iter().map(|(id, rhs)| (*id, rhs)).collect();
    let mut depths = HashMap::new();
    compute_depth_recursive(start, &prod_map, &mut depths);
    depths
}

fn compute_depth_recursive(
    node: GrammarNodeId,
    prod_map: &HashMap<GrammarNodeId, &TslpRhs>,
    depths: &mut HashMap<GrammarNodeId, usize>,
) -> usize {
    if let Some(&d) = depths.get(&node) {
        return d;
    }
    let depth = match prod_map.get(&node) {
        Some(TslpRhs::Leaf(_)) | None => 0,
        Some(TslpRhs::Eml(l, r)) => {
            let dl = compute_depth_recursive(*l, prod_map, depths);
            let dr = compute_depth_recursive(*r, prod_map, depths);
            1 + dl.max(dr)
        }
    };
    depths.insert(node, depth);
    depth
}

// ============================================================
// Tests
// ============================================================

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compress::lift::lift_bytes;
    use crate::tslp::grammar::extract_grammar;

    #[test]
    fn test_ganardi_reduces_depth_no_oom() {
        // Right-spine tree of depth 63 (N=64 bytes lifted to EML)
        let data = vec![1u8; 64];
        let tree = lift_bytes(&data);
        let unbalanced_depth = tree.depth();

        let grammar = extract_grammar(&tree);
        let g_size_before = grammar.size();

        // Must not OOM — operates only on grammar productions
        let balanced = balance_grammar(&grammar);

        let balanced_depth = balanced.max_depth();
        println!("depth: {} → {}  grammar: {} → {}",
            unbalanced_depth, balanced_depth, g_size_before, balanced.size());

        // O(log N) depth — for N=64 expect <= log2(64) * 4 = 24
        assert!(balanced_depth < unbalanced_depth,
            "Balancing must reduce depth: {} → {}", unbalanced_depth, balanced_depth);
        assert!(balanced_depth <= 24,
            "Expected O(log N) depth, got {}", balanced_depth);

        // Grammar size grows by at most O(g log g) — reasonable bound
        assert!(balanced.size() <= g_size_before * 8,
            "Grammar blowup too large: {} → {}", g_size_before, balanced.size());
    }

    #[test]
    fn test_ganardi_large_spine() {
        // K=128 right-spine → should get O(log 128) = 7 depth
        let data = vec![42u8; 128];
        let tree = lift_bytes(&data);
        let grammar = extract_grammar(&tree);
        let balanced = balance_grammar(&grammar);

        println!("K=128: depth {} → {}  grammar size: {} → {}",
            tree.depth(), balanced.max_depth(), grammar.size(), balanced.size());

        assert!(balanced.max_depth() <= 20);
    }

    #[test]
    fn test_ganardi_already_balanced_no_blowup() {
        // If input is already balanced, grammar size should not grow much
        use crate::ast::*;
        use crate::nn_layer::build_dot_product_eml;
        let k = 16;
        let weights: Vec<f32> = (0..k).map(|i| (i + 1) as f32 * 0.1).collect();
        let inputs: Vec<_> = (0..k).map(|i| var(&format!("x{}", i))).collect();
        let tree = build_dot_product_eml(&inputs, &weights);  // already balanced
        let grammar = extract_grammar(&tree);
        let balanced = balance_grammar(&grammar);

        println!("already-balanced K={}: depth {} → {}  grammar {} → {}",
            k, grammar.max_depth(), balanced.max_depth(),
            grammar.size(), balanced.size());

        // Depth should not increase
        assert!(balanced.max_depth() <= grammar.max_depth() + 3,
            "Should not significantly increase depth on balanced input");
    }
}
